### PR TITLE
#578 re-add previously deleted quads

### PR DESCRIPTION
**Pull request by gkontos**
Possible fix for #578 Unable to re-add previously deleted Quads

### CODE REVIEW

**Comment by dennwc** [comment]
Please check CI logs, there are some issues:
```
--- FAIL: TestGAEAll (34.66s)
	Error Trace:	graphtest.go:605
	Error:		Not equal: 13 (expected)
			        != 15 (actual)
	Messages:	Incorrect number of quads
```

**Comment by dennwc** [comment]
Looks good! Can you also add a sub-test to `graphtest` package that exposes an error?

**Comment by gkontos** [comment]
Yes, I should be able to do that.  The ETA is a little uncertain at the moment.

**Comment by gkontos** [comment]
So... I added a test.  However, I cannot figure out how to run the test locally (and thereby verify that it fails without the changes).  It looks like the gaedatastore test is configured to build with the following flags : // +build appengine appenginevm.  I'm not sure how to make that happen on my local machine.

**Comment by dennwc** [comment]
Travis runs the test via AppEngine SDK using this command: `goapp test -v ./graph/gaedatastore`. Is this helpful?

I'm not familiar with AppEngine to give more details.

**Comment by gkontos** [comment]
That worked wonderfully.  I confirmed that the test will fail without the updated code.

**Comment by dennwc** [comment]
Great! But I can't see the test in PR currently. Have you forgotten to include it?

**Comment by gkontos** [comment]
It appears that I did forget to include it.

**Comment by gkontos** [comment]
It sort of looks like I did something dumb in setting up the fork and pushing.  The PR contains some code that was merged from cayley master after I created my fork.  Let me know if it helps to delete this PR and submit a new clean PR.

**Comment by dennwc** [comment]
Thanks for working on this :)

**Pull request merged**
