### PR TITLE
Update transaction.go

### PR DESCRIPTION
**Pull request by h4ck3rm1k3**
spelling

### CODE REVIEW

**Comment by barakmich** [comment]
First one should be 'atomically'

**Comment by h4ck3rm1k3** [comment]
OK, I was wondering about that, but found almost no usage of that word online. How about using a longer description?

**Comment by barakmich** [comment]
Sure! Go for it!

**Comment by h4ck3rm1k3** [comment]
see second commit.

**Comment by barakmich** [comment]
Eh, better enough.

**Pull request merged**
