### PR TITLE
Reduce Docker image size

### PR DESCRIPTION
**Pull request by Yannic**
Reduce the Docker image size to about 30MB.
Requires at least Docker 17.05 to build the image.

---
This change is [Reviewable](https://reviewable.io/reviews/cayleygraph/cayley/637)

### CODE REVIEW

**Comment by dennwc** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[Dockerfile, line 13 at r1](https://reviewable.io:443/reviews/cayleygraph/cayley/637#-Kv73EJiOUznA02SjP45:-Kv73EJiOUznA02SjP46:b-gud572) ([raw file](https://github.com/cayleygraph/cayley/blob/ceff218fd7be6c51e8c13609f70ada3149ad5945/Dockerfile#L13)):*
> ```Dockerfile
> # Create filesystem for minimal image
> RUN mkdir -p /fs/assets
> RUN mkdir -p /fs/bin
> ```

add `/fs/bin` to PATH

---

*[Dockerfile, line 21 at r1](https://reviewable.io:443/reviews/cayleygraph/cayley/637#-Kv71c1zcsnI95v4oFEI:-Kv71c1zcsnI95v4oFEJ:bbkg51q) ([raw file](https://github.com/cayleygraph/cayley/blob/ceff218fd7be6c51e8c13609f70ada3149ad5945/Dockerfile#L21)):*
> ```Dockerfile
> 
> RUN mkdir -p /fs/lib/x86_64-linux-gnu
> RUN cp /lib/x86_64-linux-gnu/libc-2.24.so /fs/lib/x86_64-linux-gnu/libc-2.24.so
> ```

This exact version might not be there if `golang` image is updated. Copy it with wildcard instead.

---

*[Dockerfile, line 34 at r1](https://reviewable.io:443/reviews/cayleygraph/cayley/637#-Kv728ERsE9AZbTpBWSN:-Kv728ERsE9AZbTpBWSO:b-nrvczx) ([raw file](https://github.com/cayleygraph/cayley/blob/ceff218fd7be6c51e8c13609f70ada3149ad5945/Dockerfile#L34)):*
> ```Dockerfile
>   -ldflags="-linkmode external -extldflags -static -X github.com/cayleygraph/cayley/version.GitHash=$(git rev-parse HEAD | cut -c1-12)" \
>   -a \
>   -installsuffix cgo \
> ```

Just wondering why this is necessary.

---

*[Dockerfile, line 39 at r1](https://reviewable.io:443/reviews/cayleygraph/cayley/637#-Kv72UOuGUBY6id81SB2:-Kv72UOuGUBY6id81SB3:baj1zxi) ([raw file](https://github.com/cayleygraph/cayley/blob/ceff218fd7be6c51e8c13609f70ada3149ad5945/Dockerfile#L39)):*
> ```Dockerfile
>   ./cmd/cayley
> 
> RUN echo '{"store":{"backend":"bolt","address":"/fs/data/cayley.db"}}' > /etc/cayley.json
> ```

`bolt2`
and let's the database into `/data` (under volume) in final image

---

*[Dockerfile, line 54 at r1](https://reviewable.io:443/reviews/cayleygraph/cayley/637#-Kv72Z9FVhsek0s_KUPN:-Kv72Z9FVhsek0s_KUPO:b-j1nhf0) ([raw file](https://github.com/cayleygraph/cayley/blob/ceff218fd7be6c51e8c13609f70ada3149ad5945/Dockerfile#L54)):*
> ```Dockerfile
> EXPOSE 64210
> 
> ENTRYPOINT ["/bin/cayley", "http", "--assets", "/assets", "--host", ":64210"]
> ```

Let's do it with CMD (and call cayley from PATH):
```
ENTRYPOINT ["cayley"]
CMD ["http", "--assets", "/fs/assets", "--host", ":64210"]
```
(also fix assets dir)

---

*[internal/http/http.go, line 50 at r1](https://reviewable.io:443/reviews/cayleygraph/cayley/637#-Kv72ihu0C1JcxLsWwHE:-Kv72ihu0C1JcxLsWwHF:bb7azvd) ([raw file](https://github.com/cayleygraph/cayley/blob/ceff218fd7be6c51e8c13609f70ada3149ad5945/internal/http/http.go#L50)):*
> ```Go
> 			return AssetsPath
> 		}
> 		clog.Fatalf("Cannot find assets at %s.", AssetsPath)
> ```

`%q`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cayleygraph/cayley/637)*

**Comment by Yannic** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[Dockerfile, line 13 at r1](https://reviewable.io:443/reviews/cayleygraph/cayley/637#-Kv73EJiOUznA02SjP45:-Kv7Igl4PBlUCqc08a4n:b-a2uvb6) ([raw file](https://github.com/cayleygraph/cayley/blob/ceff218fd7be6c51e8c13609f70ada3149ad5945/Dockerfile#L13)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

add `/fs/bin` to PATH
</blockquote></details>

Not sure why this is necessary because this won't have any effect on the final image, but OK.

---

*[Dockerfile, line 21 at r1](https://reviewable.io:443/reviews/cayleygraph/cayley/637#-Kv71c1zcsnI95v4oFEI:-Kv7IjJahQRtmql2iYPM:b-896fix) ([raw file](https://github.com/cayleygraph/cayley/blob/ceff218fd7be6c51e8c13609f70ada3149ad5945/Dockerfile#L21)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

This exact version might not be there if `golang` image is updated. Copy it with wildcard instead.
</blockquote></details>

Done.

---

*[Dockerfile, line 34 at r1](https://reviewable.io:443/reviews/cayleygraph/cayley/637#-Kv728ERsE9AZbTpBWSN:-Kv7Kwhfjx5DOWW1hXBZ:btkr1zu) ([raw file](https://github.com/cayleygraph/cayley/blob/ceff218fd7be6c51e8c13609f70ada3149ad5945/Dockerfile#L34)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

Just wondering why this is necessary.
</blockquote></details>

For some reason, `go build` will produce a dynamically linked binary without this which will not run in the final image (which does not have a go runtime)​

---

*[Dockerfile, line 39 at r1](https://reviewable.io:443/reviews/cayleygraph/cayley/637#-Kv72UOuGUBY6id81SB2:-Kv7HiMGpfW41z7sH6IJ:b-5xssao) ([raw file](https://github.com/cayleygraph/cayley/blob/ceff218fd7be6c51e8c13609f70ada3149ad5945/Dockerfile#L39)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

`bolt2`
and let's the database into `/data` (under volume) in final image
</blockquote></details>

`/fs/data` in builder image will be `/data` in final image​

---

*[Dockerfile, line 54 at r1](https://reviewable.io:443/reviews/cayleygraph/cayley/637#-Kv72Z9FVhsek0s_KUPN:-Kv7G2Rpba6YMTElcSxq:b-p0r8x2) ([raw file](https://github.com/cayleygraph/cayley/blob/ceff218fd7be6c51e8c13609f70ada3149ad5945/Dockerfile#L54)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

Let's do it with CMD (and call cayley from PATH):
```
ENTRYPOINT ["cayley"]
CMD ["http", "--assets", "/fs/assets", "--host", ":64210"]
```
(also fix assets dir)
</blockquote></details>

`/fs/assets` in the builder image will be `/assets` in the final image,  no need to fix that.
(It will not work if we "fix" that)

---

*[internal/http/http.go, line 50 at r1](https://reviewable.io:443/reviews/cayleygraph/cayley/637#-Kv72ihu0C1JcxLsWwHE:-Kv7IvYeBYipyDbqOrHU:bb74ce2) ([raw file](https://github.com/cayleygraph/cayley/blob/ceff218fd7be6c51e8c13609f70ada3149ad5945/internal/http/http.go#L50)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

`%q`
</blockquote></details>

Sure

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cayleygraph/cayley/637)*

**Comment by dennwc** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[Dockerfile, line 13 at r1](https://reviewable.io:443/reviews/cayleygraph/cayley/637#-Kv73EJiOUznA02SjP45:-Kv7LheNug6TAuJJvzkj:bun27l3) ([raw file](https://github.com/cayleygraph/cayley/blob/ceff218fd7be6c51e8c13609f70ada3149ad5945/Dockerfile#L13)):*
<details><summary><i>Previously, Yannic (Yannic Bonenberger) wrote…</i></summary><blockquote>

Not sure why this is necessary because this won't have any effect on the final image, but OK.
</blockquote></details>

I meant the final image, and it looks like I misinterpreted all paths in it. If cayley binary will be in `bin`, this indeed is not very useful. But let's leave it as is.

---

*[Dockerfile, line 21 at r1](https://reviewable.io:443/reviews/cayleygraph/cayley/637#-Kv71c1zcsnI95v4oFEI:-Kv7NGzexEvxtN0rk0Uv:b493uu4) ([raw file](https://github.com/cayleygraph/cayley/blob/ceff218fd7be6c51e8c13609f70ada3149ad5945/Dockerfile#L21)):*
<details><summary><i>Previously, Yannic (Yannic Bonenberger) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`libc-*` (in other cases it will match something like `libclang`)

---

*[Dockerfile, line 34 at r1](https://reviewable.io:443/reviews/cayleygraph/cayley/637#-Kv728ERsE9AZbTpBWSN:-Kv7LxYMWsBluo5WD0Vz:b-nh059o) ([raw file](https://github.com/cayleygraph/cayley/blob/ceff218fd7be6c51e8c13609f70ada3149ad5945/Dockerfile#L34)):*
<details><summary><i>Previously, Yannic (Yannic Bonenberger) wrote…</i></summary><blockquote>

For some reason, `go build` will produce a dynamically linked binary without this which will not run in the final image (which does not have a go runtime)​
</blockquote></details>

OK, got it

---

*[Dockerfile, line 39 at r1](https://reviewable.io:443/reviews/cayleygraph/cayley/637#-Kv72UOuGUBY6id81SB2:-Kv7M3Sm4TC0yTZ2Gd0v:b-jz5krf) ([raw file](https://github.com/cayleygraph/cayley/blob/ceff218fd7be6c51e8c13609f70ada3149ad5945/Dockerfile#L39)):*
<details><summary><i>Previously, Yannic (Yannic Bonenberger) wrote…</i></summary><blockquote>

`/fs/data` in builder image will be `/data` in final image​
</blockquote></details>

But the config still points to `/fs/data`, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cayleygraph/cayley/637)*

**Comment by Yannic** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[Dockerfile, line 39 at r1](https://reviewable.io:443/reviews/cayleygraph/cayley/637#-Kv72UOuGUBY6id81SB2:-Kv7VgauMxU9SMyTBktC:b-f7fco8) ([raw file](https://github.com/cayleygraph/cayley/blob/ceff218fd7be6c51e8c13609f70ada3149ad5945/Dockerfile#L39)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

But the config still points to `/fs/data`, right?
</blockquote></details>

Thanks!
Looks like I forgot to add the config file to the final image.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cayleygraph/cayley/637)*

**Comment by dennwc** [comment]
Looks good! Let me check if image works, and I will merge it :)

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cayleygraph/cayley/637#-:-Kv7X0Z-69KhxZDoa3Om:b-o9vfjq)*

**Comment by Yannic** [comment]
That makes sense.
I also added a short explanation so that we won't have trouble remembering next time.

**Comment by dennwc** [comment]
Thanks for working on it! :)

**Pull request merged**
