### PR TITLE
GraphQL support

### LINKED ISSUE #370: Implement GraphQL
Please see it:
https://github.com/graphql-go/graphql

### PR DESCRIPTION
**Pull request by dennwc**
Adds support  for GraphQL query language. Resolves #370.

Warning: work in progress, should not be merged yet.

**TODO:**
- [x] query support
- [x] UI integration
- [x] resolve predicate naming issue
- [ ] implement fragments
- [ ] implement mutations?

### CODE REVIEW

**Comment by abourget** [comment]
Woah..  What's the state of this? That would be awesome!

**Comment by dennwc** [comment]
@abourget The state is "it works", but I need someone to test it out.

Also it would be great to have a list of must-have GraphQL features that should be implemented.

**Comment by robertmeta** [comment]
I think I am going to take this for a spin, even without fragment and mutations it is useful to us.

**Comment by evseevnn** [comment]
How soon will be released?

**Comment by dennwc** [comment]
Rebased on top of current master, and made some final modifications. Will merge shortly.

**Comment by dan-f** [comment]
How are you addressing the fact that [URIs cannot be parsed as names in GraphQL](https://facebook.github.io/graphql/#sec-Names)?

**Comment by dennwc** [comment]
@dan-f This is not strictly a GraphQL, so currently it uses a modified parser to handle IRIs and bnodes.

**Comment by steffansluis** [comment]
@dennwc Although the modified parser allows a bit more flexibility than the standard GraphQL syntax, it's still not able to process all valid IRI's, such as `http://www.w3.org/1999/02/22-rdf-syntax-ns#type`, which breaks on the `-` in the IRI.

PS: Really like the GraphQL API! :tada::+1:

**Comment by dennwc** [comment]
@steffansluis Thanks :) I'll open an issue to track parser-related problems. I'll also send a quick fix soon.

Also, as a notice, you can use `rdf:type` and it will be expanded to a full URL automatically.

**Comment by steffansluis** [comment]
@dennwc Thank you for the quick fix, but now `http://www.w3.org/1999/02/22-rdf-syntax-ns#type` is breaking on the `#` and using `rdf:type` doesn't seem to work. I've tested with the Gizmo api, the following query works fine, resulting in a multitude of node id's as a result:
```
g.V("<http://schema.org/Thing>")
	.In("<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>")
	.All()
```

Whereas the GraphQL equivalent breaks:
```
{
  nodes(id: "<http://schema.org/Thing>") {
    id
    type: <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> @rev {
  		id
  	}
  }
}
```
with the error:
`{"data":null,"errors":[{"message":"Syntax Error GraphQL (8:1) Unexpected }\n\n7:   }\n8: }\n   ^\n","locations":null}]}`

Using `rdf:type` instead (with or without `<>`), I just get a null result for the type: `{"data":{"nodes":{"id":"http://schema.org/Thing","type":null}}}`.

**Comment by stereobooster** [comment]
> This is not strictly a GraphQL, so currently it uses a modified parser to handle IRIs and bnodes.

I think we should name it GraphQL than. It can be confusing

Have you this one https://docs.dgraph.io/query-language/, but the name is horrible "GraphQL+-" (ungoogleable).

**Pull request merged**
