### PR TITLE
maxDept -1 resulted in 0 results

### PR DESCRIPTION
**Pull request by jtorvald**
should have been unlimited, according to documentation

---
This change is [Reviewable](https://reviewable.io/reviews/cayleygraph/cayley/679)

### CODE REVIEW

**Comment by dennwc** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[graph/iterator/recursive.go, line 135 at r1](https://reviewable.io:443/reviews/cayleygraph/cayley/679#-L2PPS-XvAr11e2zHPby:-L2PPS-XvAr11e2zHPbz:bmunr6w) ([raw file](https://github.com/cayleygraph/cayley/blob/26033d7f0f424ad0b6c15812da1a7dbf6eabeccb/graph/iterator/recursive.go#L135)):*
> ```Go
> 		}
> 	}
> 	if it.depth >= it.maxDepth && it.maxDepth != -1 {
> ```

Let's make it work for all negative values:
```golang
if it.maxDepth > 0 && it.depth >= it.maxDepth {
```
And zero case should be covered already by constructor.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cayleygraph/cayley/679)*

**Comment by jtorvald** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[graph/iterator/recursive.go, line 135 at r1](https://reviewable.io:443/reviews/cayleygraph/cayley/679#-L2PPS-XvAr11e2zHPby:-L2PYW4e27nCMDdmi_EQ:bfshlxr) ([raw file](https://github.com/cayleygraph/cayley/blob/26033d7f0f424ad0b6c15812da1a7dbf6eabeccb/graph/iterator/recursive.go#L135)):*
> if it.maxDepth > 0 && it.depth >= it.maxDepth {
Even better. It works.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cayleygraph/cayley/679)*

**Comment by dennwc** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[graph/iterator/recursive.go, line 135 at r1](https://reviewable.io:443/reviews/cayleygraph/cayley/679#-L2PPS-XvAr11e2zHPby:-L2Q4wpA6cZMIwK-OElX:b8dxxcp) ([raw file](https://github.com/cayleygraph/cayley/blob/26033d7f0f424ad0b6c15812da1a7dbf6eabeccb/graph/iterator/recursive.go#L135)):*
<details><summary><i>Previously, jtorvald (Jørgen) wrote…</i></summary><blockquote>

> if it.maxDepth > 0 && it.depth >= it.maxDepth {
Even better. It works.

</blockquote></details>

Can you please push an updated version?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cayleygraph/cayley/679)*

**Comment by dennwc** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cayleygraph/cayley/679#-:-L2UyKPIVrMwwkRZE-QC:bnfp4nl)*

**Pull request merged**
