### PR TITLE
make memstore threadsafe

### PR DESCRIPTION
**Pull request by dpavsrtrl**
#779

---
This change is [Reviewable](https://reviewable.io/reviews/cayleygraph/cayley/780)

### CODE REVIEW

**Comment by dennwc** [comment]
Thanks for working on it, but it may not be as straightforward as it is in this PR.

The problem is that iterators should somehow snapshot the current state of the store. In other cases, they may race with other operations like delete.

**Comment by dpavsrtrl** [comment]
No problem. This is just getting foot in the door. I'll try immutable collections.

**Comment by dpavsrtrl** [comment]
After considering the performance impact of snapshotting/persistence, perhaps it would be desirable to have two versions of memstore: current single-threaded and another, which would be concurrent.

**Comment by dpavsrtrl** [comment]
Now I believe memstore to be threadsafe, but it's certainly not consistent for concurrent writers and readers. Snapshots will require more work.

**Comment by dpavsrtrl** [comment]
These last few commits were simply inertial, I now have no intention of making current memstore threadsafe, unless it's useful for someone like this (threadsafe but not read/write concurrency consistent). I'd rather close this PR in favor of submitting another one with a new backend.

**Comment by iddan** [comment]
@dpavsrtrl so do you consider working on transactions for consistent threaded memstore?

**Comment by iddan** [comment]
@dennwc can we close this?

**Pull request closed without merging**
