### PR TITLE
Schema lib (aka ORM, aka Object Persistence Layer)

### PR DESCRIPTION
**Pull request by dennwc**
A backport of idea described in [#353](https://github.com/cayleygraph/cayley/issues/353).

Library does two things:
- Converts any Go object (with annotations) to a set of quads.
- Builds and execute queries to get the same objects from the database. 

In short, it can convert struct:

``` Go
type Item struct {
    rdfType struct{} `quad:"rdf:type > some:item"`
    ID      quad.IRI `quad:"@id"`
    Name    string   `quad:"name"`
    Spec    []string   `quad:"spec,optional"`
}
```

Into quads:

``` nquad
<some_id> <rdf:type> <some:item>
<some_id> <name> "Test name"
<some_id> <spec> "spec1"
<some_id> <spec> "spec2"
```

And query it back from the database given the same `<some_id>` and a Go struct type.

More details can be found in [original proposal](https://github.com/cayleygraph/cayley/issues/353).

As a side effect, library implements an RDF vocabulary registry (as a separate package) to expand and compact IRIs.

### CODE REVIEW

**Comment by abourget** [comment]
Couldn't:

```
rdfType struct{} `quad:"rdf:type > some:item"`
```

be simplified ? or do we need that `rdf:type > ` notation in there ?

**Comment by dennwc** [comment]
@abourget Could be simplified to:
```Go
_ struct{} `quad:"@type > some:item"`
```
This really makes a difference, right? :grin:

Actually, with the lastest commit, Go type can be bound to IRI like this:
```Go
func init(){
   schema.RegisterType(quad.IRI("some:item"), Item{})
}
```
It's essentially the same for the system - it will then generate an additional type triple each time object of type `Item` is saved and enforce the same constraint when object is loaded.
I think it would be much easier to work with then previous mechanism with struct tags. What do you think?

It worth to mention that lib can save/load structs even without a type. In this case it matches struct fields only (if they were not defined as optional).

**Comment by abourget** [comment]
yeah, like Gob registrations.. easier for newcomers.

**Comment by faddat** [comment]
I'm building a cayley that has this in it now.  Any idea when this might get into mainline?

**Comment by dennwc** [comment]
I consider it done. Feel free to comment and let's merge it!

**Comment by robertmeta** [comment]
Let me try this out, \o/

**Pull request merged**
