### PR TITLE
Add Badger as a kv store

### PR DESCRIPTION
**Pull request by fungl164**
This change is [Reviewable](https://reviewable.io/reviews/cayleygraph/cayley/763)

### CODE REVIEW

**Comment by fungl164** [comment]
Thanks! What's the target date for the Hidalgo move? I'm new to cayley. Had no idea of its existence...

**Comment by dennwc** [comment]
It's a bit hard for me to define a target date, due to a limited time I have right now, but all the code is already in `v0.8` branch, I will only need to backport it. I think 1.5 months can be an upper bound. In the meantime, we can merge this one as a backup plan.

**Comment by fungl164** [comment]
Great! Just out of curiosity...what is the preferred type of store for cayley in regards to performance, storage, processing speed, etc. (assuming no network effect)?

**Comment by fungl164** [comment]
___
*[graph/kv/badger/badger.go, line 50 at r3](https://reviewable.io/reviews/cayleygraph/cayley/763#-LYWb3dzBsEuHQoKPGaw:-LYWszH09l5l6Wqc5MYk:brycnvt) ([raw file](https://github.com/cayleygraph/cayley/blob/d93d816a4952645324f651efc6d523650c5ebf36/graph/kv/badger/badger.go#L50)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

You may also read some options from `graph.Options` argument, so they can be specified in the Cayley config file.
</blockquote></details>

There are so many options to choose from and I don't know enough about Badger to tell which are the useful ones at this point.   I would table this as an enhancement if people want to do it from a config file vs in code.

**Comment by fungl164** [comment]
___
*[graph/kv/badger/badger.go, line 109 at r3](https://reviewable.io/reviews/cayleygraph/cayley/763#-LYWaJvE0zZPlhUqKsGf:-LYWtk5z7pfbyMLCifJA:b-ly7lod) ([raw file](https://github.com/cayleygraph/cayley/blob/d93d816a4952645324f651efc6d523650c5ebf36/graph/kv/badger/badger.go#L109)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

Any particular reason to drop an error here?
</blockquote></details>

Was hoping that badger would take care of not screwing up given it successfully retrieved a value with that key. Prolly safer not to depend on hope. ; )
Would you like me to change it back?

**Comment by fungl164** [comment]
___
*[graph/kv/badger/badger.go, line 152 at r3](https://reviewable.io/reviews/cayleygraph/cayley/763#-LYWxny30CQO6rDpPP4c:-LYWxny30CQO6rDpPP4d:bmbzgpo) ([raw file](https://github.com/cayleygraph/cayley/blob/d93d816a4952645324f651efc6d523650c5ebf36/graph/kv/badger/badger.go#L152)):*
> ```Go
> 
> func (it *Iterator) Val() []byte {
> 	v, err := it.iter.Item().Value()
> ```

This should also most likely be a ValueCopy to prevent issues with badger resources after the transaction...

**Comment by dennwc** [comment]
But let me fix the CI before merging :)

**Comment by dennwc** [comment]
Sorry, the branch conflicts with the new master and the branch associated with this PR is the master of your fork, so I cannot fix it locally.

I will close this PR and merge the change manually.

Thank you for contributing it! :)

**Comment by dennwc** [comment]
Merged as https://github.com/cayleygraph/cayley/commit/682a8403b5463ad37482b5407e1985cfcd9bde33 :tada:

**Pull request closed without merging**
