### PR TITLE
Gizmo JSON-LD Content Type

### PR DESCRIPTION
**Pull request by iddan**
This change is [Reviewable](https://reviewable.io/reviews/cayleygraph/cayley/821)

### Todo
 - [x] Fix tests

### CODE REVIEW

**Comment by iddan** [comment]
It will be awesome! Can you help me to do that?

**Comment by dennwc** [comment]
Sure, will try to push changes to the same branch.

**Comment by dennwc** [comment]
@iddan I rebased your branch and exposed the new code path when `Accept: application/ld+json` is set in HTTP headers. See Gizmo's `Session.quadValueToNative` for details.

Can you please fix tests and check if HTTP endpoint returns what we expect?

I used this command to test it:
```
curl -H 'Accept: application/ld+json' 'http://localhost:64210/api/v2/query?lang=gizmo&qu=g.V("<bob>").all()'
```

**Comment by iddan** [comment]
Sure, will do it soon.

**Comment by iddan** [comment]
@dennwc tests are fixed, the response was checked

**Pull request merged**
