### PR TITLE
Glide migration

### LINKED ISSUE #451: Glide migration
We will be migrating from Godeps to Glide... Soon!

### PR DESCRIPTION
**Pull request by dennwc**
Closes #451

### CODE REVIEW

**Comment by dennwc** [comment]
@barakmich May I drop Go 1.5 from the build matrix? It seems that vendoring is not working properly there. At least `go list` leads to some strange results.

**Comment by barakmich** [comment]
You'll also want to commit glide.lock -- the yaml should tell which packages, and the lock which versions. See Torus for an example :)

**Comment by dennwc** [comment]
So I need to drop all commit hashes from glide.yml and commit lock file instead. Correct?

**Comment by barakmich** [comment]
Correct. Then, bumping current versions goes in the lock file, tracking (or locking for a good reason) a dep goes in the yaml

**Comment by barakmich** [comment]
LGTM on green

**Pull request merged**
